### ISSUE TITLE
Simple queries

### ISSUE THREAD

**Issue by MaxHalford** [gregrahn/join-order-benchmark#3]
Hello @gregrahn,

I was wondering if a "light" version of the JOB benchmark might be available. By this I mean queries that only use simple predicates such as a `=` between two attributes. I'm writing a cardinality estimation method and for the while I don't want to handle complex predicates such as `LIKE`.

Is something like this available? I thought I read about it in some paper but I seem to have forgotten...

**Comment by gregrahn** [comment]
@MaxHalford -
The closest thing that comes to my mind is the [Picasso Database Query Optimizer Visualizer](http://dsl.cds.iisc.ac.in/projects/PICASSO/index.html).

**Comment by MaxHalford** [comment]
Yes I'm aware of Picasso, but I don't think it's what I'm looking for. I was just wondering if the guys who created JOB thought of making a benchmark with trivial queries that only include `=` queries.

**Comment by gregrahn** [comment]
Not sure about that.  Sorry.

**Comment by MaxHalford** [comment]
Okay I found it. JOB-light is mentioned in at sub-section 4.5 of [this paper](https://arxiv.org/pdf/1809.00677.pdf). I'm contacting Viktor Leis to see if he can share the queries.

**Comment by gregrahn** [comment]
Cool - thanks for the reference.
