### ISSUE TITLE
wget Link not working !

### ISSUE THREAD

**Issue by Singh-AP** [gregrahn/join-order-benchmark#5]
The link in step 1 
(wget ftp://ftp.fu-berlin.de/pub/misc/movies/database/frozendata/*gz)

isn't working. I believe its been removed.
Is there any place else where its hosted?

**Comment by gregrahn** [comment]
Looks like it moved up one level -- no pub anymore:
`wget ftp://ftp.fu-berlin.de/misc/movies/database/frozendata/*gz`
should work.

**Comment by gregrahn** [comment]
Fixed via e6d4aba307a0f8849b681ccbd2ca04381d3d1731
